<div>
    <strong><?= __('Custom Sidebar') ?></strong><br>

        <?php foreach ($block->getViewModel()->getProducts() as $product): ?>

            <div class="random-products__item">
                <a class="random-products__item-img" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <img src="<?= $escaper->escapeUrl($this->helper(Magento\Catalog\Helper\Image::class)->init(
                    $product,
                    'wishlist_sidebar_block'
                )->getUrl()) ?>"
                         alt="">
                </a>

                <div class="random-products__item-info">
                    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                        <div class="random-products__item-title"><?= $escaper->escapeHtml($product->getName()) ?></div>
                    </a>
                    <div class="random-products__item-price">
                        <?= $this->helper(Magento\Framework\Pricing\Helper\Data::class)->currency(
                    $product->getFinalPrice(),
                    true,
                    false
                )
                        ?>
                    </div>
                </div>
            </div>

        <?php endforeach ?>
</div>

