<div>
    <strong>Custom Sidebar</strong><br>

        <?php foreach ($block->getViewModel()->getProducts() as $product): ?>

            <div class="random-products__item">
                <a class="random-products__item-img" href="<?= $product->getProductUrl() ?>">
                    <img src="<?= $block->getViewModel()->getProductImageUrl($product) ?>"
                        alt="">
                </a>

                <div class="random-products__item-info">
                    <a href="<?= $product->getProductUrl() ?>">
                        <div class="random-products__item-title"><?= $product->getName() ?></div>
                    </a>
                    <div class="random-products__item-price">
                        <?= '$' . number_format($product->getPrice(), 2, '.', '') ?>
                    </div>
                </div>
            </div>

        <?php endforeach ?>
</div>

