<?php

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<form class="form create account"
      action="<?= $block->getUrl('books/index/save') ?>"
      method="POST"
      autocomplete="off"
      id="book-form"
      data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset create">
        <legend class="legend"><?= __('Book Information') ?></legend>
        <br>

        <div class="field required">
            <label class="label" for="title"><?= __('Book Title') ?></label>
            <div class="control">
                <input type="text"
                       id="title"
                       name="book[title]"
                       title="<?= __('Book Title') ?>"
                       class="input-text minimum-length-2 maximum-length-225"
                       data-validate="{'required-entry':true, 'validate-length': true}">
            </div>
        </div>

        <div class="field required">
            <label class="label" for="author"><?= __('Author Name') ?></label>
            <div class="control">
                <input type="text"
                       id="author"
                       name="book[author]"
                       title="<?= __('Author Name') ?>"
                       class="input-text minimum-length-2 maximum-length-225"
                       data-validate="{'required-entry':true, 'validate-length': true}">
            </div>
        </div>

        <div class="field required">
            <label class="label" for="price"><?= __('Book Price') ?></label>
            <div class="control">
                <input type="text"
                       id="price"
                       name="book[price]"
                       title="<?= __('Book Price') ?>"
                       class="input-text digits-range-0-999999.99"
                       data-validate="{'required-entry':true, 'validate-digits-range':true}">
            </div>
        </div>

        <div class="field required">
            <label class="label" for="pages"><?= __('Total Pages') ?></label>
            <div class="control">
                <input type="text"
                       id="pages"
                       name="book[pages]"
                       title="<?= __('Total Pages') ?>"
                       class="input-text"
                       data-validate="{'required-entry':true, 'validate-digits':true}">
            </div>
        </div>
    </fieldset>

        <div class="actions-toolbar">
            <button type="submit" class="action submit primary" title="<?= __('Create Book') ?>">
                <?= __('Create Book') ?>
            </button>
        </div>
</form>


