<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Dorn\Books\ViewModel\Books\Create $viewModel
 */
$viewModel = $block->getViewModel();
?>
    <form class="form create account"
          action="<?= $viewModel->getStoreBookUrl() ?>"
          method="POST"
          autocomplete="off">
        <fieldset class="fieldset create">
            <legend class="legend">Book Information</legend><br>

            <div class="field required">
                <label class="label" for="title">Book Title</label>
                <div class="control">
                    <input type="text" id="title" name="title" title="Book Title"
                           class="input-text">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="author">Author Name</label>
                <div class="control">
                    <input type="text" id="author" name="author" title="Author Name"
                           class="input-text">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="price">Book Price</label>
                <div class="control">
                    <input type="text" id="price" name="price" title="Book Price"
                           class="input-text">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="pages">Total Pages</label>
                <div class="control">
                    <input type="text" id="pages" name="pages" title="Total Pages"
                           class="input-text">
                </div>
            </div>

        <div class="actions-toolbar">
                <button type="submit" class="action submit primary" title="Create Book">
                    <?= __('Create Book') ?>
                </button>
        </div>
    </form>


