<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Dorn\Books\ViewModel\Books\Edit $viewModel
 */
$viewModel = $block->getViewModel();
$book = $viewModel->getBook();
?>
    <form class="form create account"
          action="<?= $viewModel->getUpdateBookUrl($book->getId()) ?>"
          method="POST"
          autocomplete="off">
        <fieldset class="fieldset create">
            <legend class="legend">Update Book Information</legend><br>

            <div class="field">
                <label class="label" for="title">Book Title</label>
                <div class="control">
                    <input type="text" id="title" name="title" title="Book Title"
                           class="input-text" value="<?= $book->getTitle() ?>">
                </div>
            </div>

            <div class="field">
                <label class="label" for="author">Author Name</label>
                <div class="control">
                    <input type="text" id="author" name="author" title="Author Name"
                           class="input-text" value="<?= $book->getAuthor() ?>">
                </div>
            </div>

            <div class="field">
                <label class="label" for="price">Book Price</label>
                <div class="control">
                    <input type="text" id="price" name="price" title="Book Price"
                           class="input-text" value="<?= $book->getPrice() ?>">
                </div>
            </div>

            <div class="field">
                <label class="label" for="pages">Total Pages</label>
                <div class="control">
                    <input type="text" id="pages" name="pages" title="Total Pages"
                           class="input-text"  value="<?= $book->getPages() ?>">
                </div>
            </div>

        <div class="actions-toolbar">
                <button type="submit" class="action submit primary" title="Save">
                    <?= __('Save') ?>
                </button>
        </div>
    </form>


