<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Dorn\Books\ViewModel\Books\Edit $viewModel
 */
$viewModel = $block->getViewModel();
$book = $viewModel->getBook();
?>
    <form class="form create account"
          action="<?= $viewModel->getUpdateBookUrl($book->getId()) ?>"
          method="POST"
          autocomplete="off"
          id="book-form"
          data-mage-init='{"validation": {}}'>
        <fieldset class="fieldset create">
            <legend class="legend"><?= __('Update Book Information') ?></legend><br>

            <div class="field required">
                <label class="label" for="title"><?= __('Book Title') ?></label>
                <div class="control">
                    <input type="text" id="title"
                           name="book[title]"
                           title="<?= __('Book Title') ?>"
                           class="input-text minimum-length-2 maximum-length-225"
                           data-validate="{'required-entry':true, 'validate-length': true}"
                           value="<?= $escaper->escapeHtmlAttr($book->getTitle()) ?>">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="author"><?= __('Author Name') ?></label>
                <div class="control">
                    <input type="text" id="author"
                           name="book[author]"
                           title="<?= __('Author Name') ?>"
                           class="input-text minimum-length-2 maximum-length-225"
                           data-validate="{'required-entry':true, 'validate-length': true}"
                           value="<?= $escaper->escapeHtmlAttr($book->getAuthor()) ?>">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="price"><?= __('Book Price') ?></label>
                <div class="control">
                    <input type="text"
                           id="price"
                           name="book[price]"
                           title="<?= __('Book Price') ?>"
                           class="input-text digits-range-0-999999.99"
                           data-validate="{'required-entry':true, 'validate-digits-range':true}"
                           value="<?= $escaper->escapeHtmlAttr($book->getPrice()) ?>">
                </div>
            </div>

            <div class="field required">
                <label class="label" for="pages"><?= __('Total Pages') ?></label>
                <div class="control">
                    <input type="text"
                           id="pages"
                           name="book[pages]"
                           title="<?= __('Total Pages') ?>"
                           class="input-text"
                           data-validate="{'required-entry':true, 'validate-digits':true}"
                           value="<?= $escaper->escapeHtmlAttr($book->getPages()) ?>">
                </div>
            </div>

        <div class="actions-toolbar">
                <button type="submit" class="action submit primary" title="<?= __('Save') ?>">
                    <?= __('Save') ?>
                </button>
        </div>
    </form>


